language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: stable
      name: "Linux, stable"
      install:
        - rustup target add thumbv6m-none-eabi
      script:
        - cargo build --target thumbv6m-none-eabi --verbose
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
