[package]
name = "beef"
version = "0.1.3"
authors = ["Maciej Hirsz <hello@maciej.codes>"]
edition = "2018"
description = "More compact Cow"
repository = "https://github.com/maciejhirsz/beef"
documentation = "https://docs.rs/json/"
license = "MIT/Apache-2.0"

[features]
default = []

# makes `Cow::borrowed` a const fn
# requires nightly: https://github.com/rust-lang/rust/issues/57563
const_fn = []
